---
abstract: 'A POE filter wrapped around Compress::LZW'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-LZW
no_index:
  directory:
    - inc
    - t
provides:
  POE::Filter::LZW:
    file: lib/POE/Filter/LZW.pm
    version: 1.72
requires:
  Compress::LZW: 0
  POE: 0.38
  POE::Filter: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-filter-lzw/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-lzw.git
version: 1.72
