---
abstract: 'A POE filter wrapped around Compress::LZW'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Filter-LZW
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Compress::LZW: 0
  POE: 0.38
  POE::Filter: 0
version: 1.70
