author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Filter::LZW
name: POE-Filter-LZW
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Compress::LZW: 0
  POE: 0.3501
version: 1.5
